### ISSUE TITLE
Running project on iOS with XCode

### ISSUE THREAD

**Issue by jankoritak** [mratsim/ReactFincal#1]
Hi,

any chance you can wrap ReactFinal with XCode project, so it can be run on iOS Simulator?

Thanks!

**Comment by mratsim** [comment]
Sorry I only catched your comment today (yeah I know :/)

Normally I tested at the time, if you do
```
react-native init ReactFincal
```
and then
```
react-native run-ios
```
it should configure all the Xcode parts

I followed that tutorial: https://kylewbanks.com/blog/react-native-tutorial-part-1-hello-react and customized its calculator to support typescript and operator precedence. So setup is the same.
